# In _config.yml
title: Forecasting long-term ED demand
author: Charlotte James
execute:
  execute_notebooks: auto

launch_buttons:
  colab_url: https://colab.research.google.com

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib
